# Generated by Django 5.2.6 on 2025-09-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_roles_alter_users_options_remove_users_role_userrole"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrole",
            old_name="user_id",
            new_name="user",
        ),
    ]
