# Generated by Django 5.2.6 on 2025-09-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        ("users", "0004_roles_alter_users_options_remove_users_role_userrole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrole",
            name="role",
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.roles"
            ),
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
