# Generated by Django 5.2.6 on 2025-09-17 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_books_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="volume",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="categoryprice",
            name="price_per_day",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
