# Generated by Django 5.2.6 on 2025-09-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_booksuserstransactions_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksuserstransactions",
            name="transaction_type",
            field=models.CharField(
                choices=[("borrow", "Borrow"), ("return", "Return")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="categoryprice",
            name="category",
            field=models.CharField(
                choices=[
                    ("manga", "Manga"),
                    ("comics", "Comics"),
                    ("non-fiction", "Non-Fiction"),
                    ("educational", "Educational"),
                    ("magazine", "Magazine"),
                    ("novel", "Novel"),
                ],
                max_length=20,
            ),
        ),
    ]
