# Generated by Django 5.2.6 on 2025-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_booksuserstransactions_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booksuserstransactions",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.CharField(default="oda", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoryprice",
            name="category",
            field=models.CharField(
                choices=[
                    ("manga", "Manga"),
                    ("comics", "Comics"),
                    ("non-fiction", "Non-Fiction"),
                    ("educational", "Educational"),
                    ("magazine", "Magazine"),
                    ("novel", "Novel"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
