# Generated by Django 5.2.6 on 2025-09-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_booksuserstransactions_options_books_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="genre",
        ),
    ]
